language: node_js
env:
  - MOBX_VERSION=4
  - MOBX_VERSION=5
  - MOBX_VERSION=6
install:
  - node version-switcher.js $MOBX_VERSION
  - yarn
script: 
  - pushd packages/computed-async-mobx
  - yarn test
  - popd
after_success:
  - pushd packages/computed-async-mobx
  - yarn coverage
  - popd
node_js:
  - 14
